name: sheet_to_api
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  dio: ^5.5.0+1
#   path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
