# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: master

on:
  # push:
  #   branches:
  #     - '*'
  # schedule:
  #   - cron: "0 */2 * * *"
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Get branch name (merge)
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Install dependencies
        run: dart pub get
      - name: Fetch API
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: dart run
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: hautvfami
          author_email: hautv.fami@gmail.com
          message: 'Update'
          add: 'data/*.json'
      # # Deploy
      # - uses: meeDamian/github-release@2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ env.BRANCH_NAME }}_release
      #     # name: ${{ env.BRANCH_NAME }}_release
      #     allow_override: true

      # - name: Upload binaries to release
      #   uses: xresloader/upload-to-github-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     file: "data/*.json"
      #     tags: true
      #     tag_name: ${{ env.BRANCH_NAME }}_release
      #     overwrite: true